// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

#pragma warning disable CS0618 // Type or member is obsolete

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class EWMDbCtx : DbContext
{
    public EWMDbCtx(DbContextOptions<EWMDbCtx> options)
        : base(options)
    {
    }

    public virtual DbSet<Bin> Bins { get; set; }

    public virtual DbSet<Component> Components { get; set; }

    public virtual DbSet<ComponentBin> ComponentBins { get; set; }

    public virtual DbSet<ComponentCategory> ComponentCategories { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<TransferRequest> TransferRequests { get; set; }

    public virtual DbSet<TransferRequestComponent> TransferRequestComponents { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bin>(entity =>
        {
            entity.ToTable("Bin");

            entity.Property(e => e.BinId).HasColumnName("bin_id");
            entity.Property(e => e.LocationInWarehouse)
                .IsRequired()
                .HasColumnName("location_in_warehouse");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Bins)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bin_Warehouse");
        });

        modelBuilder.Entity<Component>(entity =>
        {
            entity.ToTable("Component");

            entity.Property(e => e.ComponentId).HasColumnName("component_id");
            entity.Property(e => e.MetadataJson)
                .IsRequired()
                .HasColumnName("metadata_json");
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("unit");
            entity.Property(e => e.UnitPrice).HasColumnName("unit_price");

            entity.HasMany(d => d.Categories).WithMany(p => p.Components)
                .UsingEntity<Dictionary<string, object>>(
                    "CC",
                    r => r.HasOne<ComponentCategory>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_C_C_ComponentCategory"),
                    l => l.HasOne<Component>().WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_C_C_Component"),
                    j =>
                    {
                        j.HasKey("ComponentId", "CategoryId");
                        j.ToTable("C_C");
                        j.IndexerProperty<int>("ComponentId").HasColumnName("component_id");
                        j.IndexerProperty<int>("CategoryId").HasColumnName("category_id");
                    });
        });

        modelBuilder.Entity<ComponentBin>(entity =>
        {
            entity.ToTable("ComponentBin");

            entity.Property(e => e.ComponentBinId).HasColumnName("component_bin_id");
            entity.Property(e => e.BinId).HasColumnName("bin_id");
            entity.Property(e => e.ComponentId).HasColumnName("component_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.Bin).WithMany(p => p.ComponentBins)
                .HasForeignKey(d => d.BinId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ComponentBin_Bin");

            entity.HasOne(d => d.Component).WithMany(p => p.ComponentBins)
                .HasForeignKey(d => d.ComponentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ComponentBin_Component");
        });

        modelBuilder.Entity<ComponentCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("ComponentCategory");

            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("category_name");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<TransferRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId);

            entity.ToTable("TransferRequest");

            entity.Property(e => e.RequestId).HasColumnName("request_id");
            entity.Property(e => e.ApproverId).HasColumnName("approver_id");
            entity.Property(e => e.BinFromId).HasColumnName("bin_from_id");
            entity.Property(e => e.BinToId).HasColumnName("bin_to_id");
            entity.Property(e => e.CreationTime)
                .HasColumnType("datetime")
                .HasColumnName("creation_time");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.ExecutionTime)
                .HasColumnType("datetime")
                .HasColumnName("execution_time");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.TypeInt).HasColumnName("type_int");

            entity.HasOne(d => d.Approver).WithMany(p => p.TransferRequestApprovers)
                .HasForeignKey(d => d.ApproverId)
                .HasConstraintName("FK_TransferRequest_User_Approver");

            entity.HasOne(d => d.BinFrom).WithMany(p => p.TransferRequestBinFroms)
                .HasForeignKey(d => d.BinFromId)
                .HasConstraintName("FK_TransferRequest_Bin_From");

            entity.HasOne(d => d.BinTo).WithMany(p => p.TransferRequestBinTos)
                .HasForeignKey(d => d.BinToId)
                .HasConstraintName("FK_TransferRequest_Bin_To");

            entity.HasOne(d => d.Creator).WithMany(p => p.TransferRequestCreators)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TransferRequest_User_Creator");
        });

        modelBuilder.Entity<TransferRequestComponent>(entity =>
        {
            entity.ToTable("TransferRequestComponent");

            entity.Property(e => e.TransferRequestComponentId).HasColumnName("transfer_request_component_id");
            entity.Property(e => e.ComponentId).HasColumnName("component_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.RequestId).HasColumnName("request_id");
            entity.Property(e => e.UnitPrice).HasColumnName("unit_price");

            entity.HasOne(d => d.Component).WithMany(p => p.TransferRequestComponents)
                .HasForeignKey(d => d.ComponentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TransferRequestComponent_Component");

            entity.HasOne(d => d.Request).WithMany(p => p.TransferRequestComponents)
                .HasForeignKey(d => d.RequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TransferRequestComponent_TransferRequest");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnName("email");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("username");

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UR",
                    r => r.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_U_R_Role"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_U_R_User"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("U_R");
                        j.IndexerProperty<int>("UserId").HasColumnName("user_id");
                        j.IndexerProperty<int>("RoleId").HasColumnName("role_id");
                    });
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.ToTable("Warehouse");

            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(1000)
                .HasColumnName("image_url");
            entity.Property(e => e.PhysicalLocation)
                .IsRequired()
                .HasColumnName("physical_location");
            entity.Property(e => e.WarehouseName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("warehouse_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

#pragma warning restore CS0618 // Type or member is obsolete