// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

#pragma warning disable CS0618 // Type or member is obsolete

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class EWMDbCtx : DbContext
{
    public EWMDbCtx(DbContextOptions<EWMDbCtx> options)
        : base(options)
    {
    }

    public virtual DbSet<Bin> Bins { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<ItemDefinition> ItemDefinitions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<TransferReq> TransferReqs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Warehouse> Warehouses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bin>(entity =>
        {
            entity.ToTable("Bin");

            entity.Property(e => e.BinId).HasColumnName("bin_id");
            entity.Property(e => e.LocationInWarehouse)
                .IsRequired()
                .HasColumnName("location_in_warehouse");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");

            entity.HasOne(d => d.Warehouse).WithMany(p => p.Bins)
                .HasForeignKey(d => d.WarehouseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bin_Warehouse");

            entity.HasMany(d => d.Items).WithMany(p => p.Bins)
                .UsingEntity<Dictionary<string, object>>(
                    "ItemBin",
                    r => r.HasOne<Item>().WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ItemBin_Item"),
                    l => l.HasOne<Bin>().WithMany()
                        .HasForeignKey("BinId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ItemBin_Bin"),
                    j =>
                    {
                        j.HasKey("BinId", "ItemId");
                        j.ToTable("ItemBin");
                        j.IndexerProperty<int>("BinId").HasColumnName("bin_id");
                        j.IndexerProperty<int>("ItemId").HasColumnName("item_id");
                    });
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("category_name");

            entity.HasMany(d => d.ItemDefs).WithMany(p => p.Categories)
                .UsingEntity<Dictionary<string, object>>(
                    "ItemCategory",
                    r => r.HasOne<ItemDefinition>().WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ItemCategory_ItemDefinition"),
                    l => l.HasOne<Category>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ItemCategory_Category"),
                    j =>
                    {
                        j.HasKey("CategoryId", "ItemDefId");
                        j.ToTable("ItemCategory");
                        j.IndexerProperty<int>("CategoryId").HasColumnName("category_id");
                        j.IndexerProperty<int>("ItemDefId").HasColumnName("item_def_id");
                    });
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.ToTable("Item");

            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.ItemDefId).HasColumnName("item_def_id");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.ItemDef).WithMany(p => p.Items)
                .HasForeignKey(d => d.ItemDefId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Item_ItemDefinition");

            entity.HasMany(d => d.Transfers).WithMany(p => p.Items)
                .UsingEntity<Dictionary<string, object>>(
                    "TransferReqItem",
                    r => r.HasOne<TransferReq>().WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TransferReqItem_TransferReq"),
                    l => l.HasOne<Item>().WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TransferReqItem_Item"),
                    j =>
                    {
                        j.HasKey("ItemId", "TransferId");
                        j.ToTable("TransferReqItem");
                        j.IndexerProperty<int>("ItemId").HasColumnName("item_id");
                        j.IndexerProperty<int>("TransferId").HasColumnName("transfer_id");
                    });
        });

        modelBuilder.Entity<ItemDefinition>(entity =>
        {
            entity.HasKey(e => e.ItemDefId);

            entity.ToTable("ItemDefinition");

            entity.Property(e => e.ItemDefId).HasColumnName("item_def_id");
            entity.Property(e => e.MetadataJson)
                .IsRequired()
                .HasColumnName("metadata_json");
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("unit");
            entity.Property(e => e.UnitPrice).HasColumnName("unit_price");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");

            entity.HasMany(d => d.Users).WithMany(p => p.Roles)
                .UsingEntity<Dictionary<string, object>>(
                    "UserRole",
                    r => r.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UserRole_User"),
                    l => l.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UserRole_Role"),
                    j =>
                    {
                        j.HasKey("RoleId", "UserId");
                        j.ToTable("UserRole");
                        j.IndexerProperty<int>("RoleId").HasColumnName("role_id");
                        j.IndexerProperty<int>("UserId").HasColumnName("user_id");
                    });
        });

        modelBuilder.Entity<TransferReq>(entity =>
        {
            entity.HasKey(e => e.TransferId);

            entity.ToTable("TransferReq");

            entity.Property(e => e.TransferId).HasColumnName("transfer_id");
            entity.Property(e => e.ApproverId).HasColumnName("approver_id");
            entity.Property(e => e.CreationDate).HasColumnName("creation_date");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.ExecutionDate).HasColumnName("execution_date");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.TypeInt).HasColumnName("type_int");
            entity.Property(e => e.WarehouseFromId).HasColumnName("warehouse_from_id");
            entity.Property(e => e.WarehouseToId).HasColumnName("warehouse_to_id");

            entity.HasOne(d => d.Approver).WithMany(p => p.TransferReqApprovers)
                .HasForeignKey(d => d.ApproverId)
                .HasConstraintName("FK_TransferReq_User1");

            entity.HasOne(d => d.Creator).WithMany(p => p.TransferReqCreators)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TransferReq_User");

            entity.HasOne(d => d.WarehouseFrom).WithMany(p => p.TransferReqWarehouseFroms)
                .HasForeignKey(d => d.WarehouseFromId)
                .HasConstraintName("FK_TransferReq_Warehouse");

            entity.HasOne(d => d.WarehouseTo).WithMany(p => p.TransferReqWarehouseTos)
                .HasForeignKey(d => d.WarehouseToId)
                .HasConstraintName("FK_TransferReq_Warehouse1");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("password_hash");
            entity.Property(e => e.StatusInt).HasColumnName("status_int");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Warehouse>(entity =>
        {
            entity.ToTable("Warehouse");

            entity.Property(e => e.WarehouseId).HasColumnName("warehouse_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(4000)
                .HasColumnName("image_url");
            entity.Property(e => e.PhysicalLocation)
                .IsRequired()
                .HasColumnName("physical_location");
            entity.Property(e => e.WarehouseName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("warehouse_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

#pragma warning restore CS0618 // Type or member is obsolete