// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Bin
{
    public int BinId { get; set; }

    public string LocationInWarehouse { get; set; }

    [Obsolete("Use Status instead.")]
    public int StatusInt { get; set; }

    public int WarehouseId { get; set; }

    public virtual ICollection<ComponentBin> ComponentBins { get; set; } = new List<ComponentBin>();

    public virtual ICollection<TransferRequest> TransferRequestBinFroms { get; set; } = new List<TransferRequest>();

    public virtual ICollection<TransferRequest> TransferRequestBinTos { get; set; } = new List<TransferRequest>();

    public virtual Warehouse Warehouse { get; set; }
}