// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Bin
{
    public int BinId { get; set; }

    public string LocationInWarehouse { get; set; }

    public int Status { get; set; }

    public int WarehouseId { get; set; }

    public virtual Warehouse Warehouse { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}