// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Component
{
    public int ComponentId { get; set; }

    [Obsolete("Use Metadata instead.")]
    public string MetadataJson { get; set; }

    public string Unit { get; set; }

    public double UnitPrice { get; set; }

    public virtual ICollection<ComponentBin> ComponentBins { get; set; } = new List<ComponentBin>();

    public virtual ICollection<TransferRequestComponent> TransferRequestComponents { get; set; } = new List<TransferRequestComponent>();

    public virtual ICollection<ComponentCategory> Categories { get; set; } = new List<ComponentCategory>();
}