// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class ComponentCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Component> Components { get; set; } = new List<Component>();
}