// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class ComponentBin
{
    public int ComponentBinId { get; set; }

    public double Quantity { get; set; }

    public int ComponentId { get; set; }

    public int BinId { get; set; }

    public virtual Bin Bin { get; set; }

    public virtual Component Component { get; set; }
}