// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class FinishedTransferRequestComponent
{
    public int FinishedTransferRequestComponentId { get; set; }

    public int RequestId { get; set; }

    public int ComponentId { get; set; }

    public int BinId { get; set; }

    public double Quantity { get; set; }

    [Obsolete("Use Type instead.")]
    public int TypeInt { get; set; }

    public virtual Bin Bin { get; set; }

    public virtual Component Component { get; set; }

    public virtual TransferRequest Request { get; set; }
}