// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class ItemDefinition
{
    public int ItemDefId { get; set; }

    [Obsolete("Use Metadata instead.")]
    public string MetadataJson { get; set; }

    public string Unit { get; set; }

    public float UnitPrice { get; set; }

    private ComponentMetadata? _metadata;
    [NotMapped]
    public ComponentMetadata? Metadata
    {
        get
        {
            if (_metadata == null && !string.IsNullOrEmpty(MetadataJson))
            {
                try
                {
                    _metadata = JsonSerializer.Deserialize<ComponentMetadata>(MetadataJson);
                }
                catch
                {
                    _metadata = new ComponentMetadata();
                }
            }
            return _metadata;
        }
        set => _metadata = value;
    }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}