// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Item
{
    public int ItemId { get; set; }

    public float Quantity { get; set; }

    public int ItemDefId { get; set; }

    public virtual ItemDefinition ItemDef { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual ICollection<TransferReq> Transfers { get; set; } = new List<TransferReq>();
}