// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class ItemDefinition
{
    public int ItemDefId { get; set; }

    [Obsolete("Use Metadata instead.")]
    public string MetadataJson { get; set; }

    public string Unit { get; set; }

    public float UnitPrice { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}