// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Item
{
    public int ItemId { get; set; }

    public string Metadata { get; set; }

    public int Quantity { get; set; }

    public string Unit { get; set; }

    public DateOnly ImportDate { get; set; }

    public float UnitPrice { get; set; }

    public int? TransferId { get; set; }

    public int? IobId { get; set; }

    public virtual InOutBoundReq Iob { get; set; }

    public virtual TransferReq Transfer { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}