// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class TransferRequest
{
    public int RequestId { get; set; }

    public string Description { get; set; }

    [Obsolete("Use Type instead.")]
    public int TypeInt { get; set; }

    public DateTime CreationTime { get; set; }

    public DateTime? ExecutionTime { get; set; }

    [Obsolete("Use Status instead.")]
    public int StatusInt { get; set; }

    public int CreatorId { get; set; }

    public int? ApproverId { get; set; }

    public int? WarehouseFromId { get; set; }

    public int? WarehouseToId { get; set; }

    public int? CustomerId { get; set; }

    public virtual User Approver { get; set; }

    public virtual User Creator { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<FinishedTransferRequestComponent> FinishedTransferRequestComponents { get; set; } = new List<FinishedTransferRequestComponent>();

    public virtual ICollection<TransferRequestComponent> TransferRequestComponents { get; set; } = new List<TransferRequestComponent>();

    public virtual Warehouse WarehouseFrom { get; set; }

    public virtual Warehouse WarehouseTo { get; set; }
}