// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class TransferReq
{
    public int TransferId { get; set; }

    public string Description { get; set; }

    [Obsolete("Use Type instead.")]
    public int TypeInt { get; set; }

    public DateOnly CreationDate { get; set; }

    public DateOnly? ExecutionDate { get; set; }

    [Obsolete("Use Status instead.")]
    public int StatusInt { get; set; }

    public int CreatorId { get; set; }

    public int? ApproverId { get; set; }

    public int? WarehouseFromId { get; set; }

    public int? WarehouseToId { get; set; }

    public virtual User Approver { get; set; }

    public virtual User Creator { get; set; }

    public virtual Warehouse WarehouseFrom { get; set; }

    public virtual Warehouse WarehouseTo { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}