// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    [Obsolete("Use Status instead.")]
    public int StatusInt { get; set; }

    public virtual ICollection<TransferReq> TransferReqApprovers { get; set; } = new List<TransferReq>();

    public virtual ICollection<TransferReq> TransferReqCreators { get; set; } = new List<TransferReq>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}