// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class InOutBoundReq
{
    public int IobId { get; set; }

    public string Description { get; set; }

    public int Type { get; set; }

    public DateOnly? ExecutionDate { get; set; }

    public DateOnly CreationDate { get; set; }

    public int Staus { get; set; }

    public int CreatorId { get; set; }

    public int ApproverId { get; set; }

    public int WarehouseId { get; set; }

    public virtual User Approver { get; set; }

    public virtual User Creator { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual Warehouse Warehouse { get; set; }
}