// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectronicsWarehouseManagement.Repositories.Entities;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string Description { get; set; }

    public string PhysicalLocation { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Bin> Bins { get; set; } = new List<Bin>();

    public virtual ICollection<InOutBoundReq> InOutBoundReqs { get; set; } = new List<InOutBoundReq>();

    public virtual ICollection<TransferReq> TransferReqWarehouseFroms { get; set; } = new List<TransferReq>();

    public virtual ICollection<TransferReq> TransferReqWarehouseTos { get; set; } = new List<TransferReq>();
}